### ISSUE TITLE
Problem with component class

### ISSUE THREAD

**Issue by Nightenom** [Swedz/tesseract-neoforge#37]
Hello,
could you please consider either extending `MutableComponent` or even better using and extending `ComponentContents` instead (that's what vanilla do)? Thank you
Related crash: https://github.com/ldtteam/BlockUI/issues/104

**Comment by Swedz** [comment]
The reason I use Component instead of MutableComponent is because my TextLines are not meant to be mutable. Making them MutableComponents and retaining my current functionality I have set for them would certainly create more issues where people expect them to be mutable when they technically aren't. It would take quite a bit of changes on my end, but its not _that_ unreasonable. Using ComponentContents doesn't allow me to use styling and to add my TextLines directly to tooltips without having to use extra bloat to convert them to Components.

I'm not entirely opposed to making this change of making TextLines mutable, but it might be better practice if BlockUI didn't assume all Components are MutableComponents [here](https://github.com/ldtteam/BlockUI/blob/cc8ed885229f8db0151616aa51b061fc70868fc8/src/main/java/com/ldtteam/blockui/controls/AbstractTextElement.java#L495-L515). Something like `text instanceof MutableComponent mutable ? mutable : text.copy()` would be simple enough I think?

**Comment by Nightenom** [comment]
I mean technically blockui can be only on Component, but consumer mods would have to cast every getter + it's vanilla design to have everything as MutableComponent and ComponentContents, which if implemented using record are immutable (note we are using it ourselves like this, but only for our UI components - eg. https://github.com/ldtteam/BlockUI/blob/version/main/src/main/java/com/ldtteam/blockui/util/SpacerTextComponent.java)
Could you please describe what is the purpose of your TextLine classes? Looking at code I don't see anything that would make TextLine any different compared to Component.translatable (apart from immutability)

**Comment by Swedz** [comment]
I was saying the highlighted input methods cast from Component to MutableComponent without any check of any kind in AbstractTextElement. I wasn't recommending you change from using MutableComponents to Components lol.

The purpose of the TextLine classes are to simplify component formatting. It uses custom parsers and some examples of those can be seen [here](https://github.com/Swedz/tesseract-neoforge/blob/1.21.1/src/main/java/net/swedz/tesseract/neoforge/tooltip/Parser.java) and [here](https://github.com/Swedz/Extended-Industrialization/blob/5f95ad27a00b28b7fb7139ce1bf6fca115f061ca/src/main/java/net/swedz/extended_industrialization/EITooltips.java#L28-L47). TextLine itself uses Component so it can be used directly without having to do additional conversions like you do in your SpacerTextComponent. [Here's](https://github.com/Swedz/Extended-Industrialization/blob/1.21.1/src/main/java/net/swedz/extended_industrialization/item/nanosuit/NanoSuitSpeedAbility.java#L55) an example of what I mean by that.

**Comment by Swedz** [comment]
I don't plan on making this change so I'm closing this. If you want to fix this, you can do the one line change solution I presented in a previous comment. :)

**Comment by Nightenom** [comment]
Firstly, thank you for insights on your code, well, surely we can add the casting
Secondly and nevertheless I still don't see the point behind your design (I would eg. understand if it would be for delayed or dynamic arg evaluation) imho same could be done using plain builder approach which would even eliminate the need for extending the Component at all. In any other case you could use ComponentContents because it was also designed for things like lazy eval etc.
